// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkpfbiwqgywgmfgbbitg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcGZiaXdxZ3l3Z21mZ2JiaXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTQ3OTAsImV4cCI6MjA3MzgzMDc5MH0.JPTSXgQasaKJVBNqjz77QtwKF4jCLRtZHTxx8L8tWpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});